"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.userRoutes = void 0;
const express_1 = require("express");
const user_schema_1 = require("../schemas/user.schema");
const middlewares_1 = require("../middlewares");
const user_1 = require("../controllers/user");
const retrieveOneUser_controller_1 = require("../controllers/user/retrieveOneUser.controller");
exports.userRoutes = (0, express_1.Router)();
exports.userRoutes.post("", (0, middlewares_1.ensureDataIsValidMiddleware)(user_schema_1.userSchemaRequest), middlewares_1.ensureEmailExistsMiddleware, user_1.createUserController);
exports.userRoutes.get("", user_1.retrieveUserController);
exports.userRoutes.get("/:id", middlewares_1.ensureUserExistsMiddleware, retrieveOneUser_controller_1.retrieveOneUserController);
exports.userRoutes.patch("/:id", (0, middlewares_1.ensureDataIsValidMiddleware)(user_schema_1.userSchemaUpdate), middlewares_1.ensureEmailExistsMiddleware, user_1.updateUserController);
exports.userRoutes.delete("/:id", middlewares_1.ensureUserExistsMiddleware, user_1.deleteUserController);
