"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.listAllCommentController = exports.listAllUserCommentsController = exports.deleteCommentController = exports.updateCommentController = exports.createCommentController = void 0;
const create_controller_1 = require("./create.controller");
Object.defineProperty(exports, "createCommentController", { enumerable: true, get: function () { return create_controller_1.createCommentController; } });
const update_controller_1 = require("./update.controller");
Object.defineProperty(exports, "updateCommentController", { enumerable: true, get: function () { return update_controller_1.updateCommentController; } });
const delete_controller_1 = require("./delete.controller");
Object.defineProperty(exports, "deleteCommentController", { enumerable: true, get: function () { return delete_controller_1.deleteCommentController; } });
const listAdComments_controller_1 = require("./listAdComments.controller");
Object.defineProperty(exports, "listAllUserCommentsController", { enumerable: true, get: function () { return listAdComments_controller_1.listAllUserCommentsController; } });
const listAllComments_controller_1 = require("./listAllComments.controller");
Object.defineProperty(exports, "listAllCommentController", { enumerable: true, get: function () { return listAllComments_controller_1.listAllCommentController; } });
